## Part 1: Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [2]:
# Determine the number of unique values in each column
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [ ]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']].copy()
y_df.head()

Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [22]:

y_df['Attrition'].value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [23]:
y_df['Department'].value_counts()

Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

In [4]:
# Create a list of at least 10 column names to use as X data
x_columns = ['Age', 'DistanceFromHome', 'Education', 'EnvironmentSatisfaction', 'JobInvolvement',
              'JobLevel', 'JobSatisfaction', 'NumCompaniesWorked', 'PerformanceRating', 'TotalWorkingYears']

# Create X_df using your selected columns
X_df = attrition_df[x_columns].copy()

# Show the data types for X_df
X_df.dtypes

Age                        int64
DistanceFromHome           int64
Education                  int64
EnvironmentSatisfaction    int64
JobInvolvement             int64
JobLevel                   int64
JobSatisfaction            int64
NumCompaniesWorked         int64
PerformanceRating          int64
TotalWorkingYears          int64
dtype: object

In [5]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size=0.2, random_state=42)

In [ ]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary
#No Need to do this step as all columns are already numeric

OverTime
No     797
Yes    305
Name: count, dtype: int64

In [6]:
# Create a StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
x_scaler = scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = x_scaler.transform(X_train)
X_test_scaled = x_scaler.transform(X_test)

In [9]:
from sklearn.preprocessing import OneHotEncoder

# Create a OneHotEncoder for the Department column
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore',drop=None)


# Fit the encoder to the training data
encoder.fit(np.array(y_train['Department']).reshape(-1, 1))

# Create two new variables by applying the encoder
# to the training and testing data
y_department_train = encoder.transform(np.array(y_train['Department']).reshape(-1, 1))
y_department_test = encoder.transform(np.array(y_test['Department']).reshape(-1, 1))
print(y_department_train[:10])

[[0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [10]:
# Create a OneHotEncoder for the Attrition column
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore',drop=None)

# Fit the encoder to the training data
encoder.fit(np.array(y_train['Attrition']).reshape(-1, 1))

# Create two new variables by applying the encoder
# to the training and testing data
y_attrition_train = encoder.transform(np.array(y_train['Attrition']).reshape(-1, 1))
y_attrition_test = encoder.transform(np.array(y_test['Attrition']).reshape(-1, 1))
print(y_attrition_train[:10])

[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]


## Part 2: Create, Compile, and Train the Model

In [11]:
# Find the number of columns in the X training data.
Number_of_columns = len(X_train.columns)
# Create the input layer
input_layer = layers.Input(shape=(Number_of_columns,), name='input_layer')

# Create at least two shared layers
shared_layer_1 = layers.Dense(64, activation='relu', name='shared_layer_1')(input_layer)
shared_layer_2 = layers.Dense(128, activation='relu', name='shared_layer_2')(shared_layer_1)

In [12]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer
department_hidden_layer = layers.Dense(64, activation='relu', name='department_hidden_layer')(shared_layer_2)


# Create the output layer
department_output_layer = layers.Dense(y_department_train.shape[1], activation='softmax', name='department_output_layer')(department_hidden_layer)

In [24]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer
attrition_hidden_layer = layers.Dense(64, activation='relu', name='attrition_hidden_layer')(shared_layer_2)

# Create the output layer
attrition_output_layer = layers.Dense(y_attrition_train.shape[1], activation='sigmoid', name='attrition_output_layer')(attrition_hidden_layer)

In [26]:
# Create the model

model = Model(inputs=input_layer, outputs={'department_output_layer': department_output_layer, 'attrition_output_layer': attrition_output_layer})
# Compile the model
model.compile(optimizer='adam', loss={'department_output_layer': 'categorical_crossentropy', 'attrition_output_layer': 'binary_crossentropy'}, 
              metrics={'department_output_layer': 'accuracy', 'attrition_output_layer': 'accuracy'})

# Summarize the model
model.summary()

Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 10)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ shared_layer_1      │ (None, 64)        │        704 │ input_layer[0][0] │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ shared_layer_2      │ (None, 128)       │      8,320 │ shared_layer_1[0… │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attrition_hidden_l… │ (None, 64)        │      8,256 │ shared_layer_2[0… │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ department_hidden_… │ (None, 64)        │      8,256 │ shared_layer_2[0… │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attrition_output_l… │ (None, 2)         │        130 │ attrition_hidden… │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ department_output_… │ (None, 3)         │        195 │ department_hidde… │
│ (Dense)             │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 25,861 (101.02 KB)

 Trainable params: 25,861 (101.02 KB)

 Non-trainable params: 0 (0.00 B)

In [27]:
# Train the model
fit_history = model.fit(X_train_scaled, {'department_output_layer': y_department_train, 'attrition_output_layer': y_attrition_train},
                        epochs=100)

Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - attrition_output_layer_accuracy: 0.7971 - attrition_output_layer_loss: 0.5074 - department_output_layer_accuracy: 0.9879 - department_output_layer_loss: 0.0477 - loss: 0.5550
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - attrition_output_layer_accuracy: 0.8264 - attrition_output_layer_loss: 0.4143 - department_output_layer_accuracy: 0.9881 - department_output_layer_loss: 0.0377 - loss: 0.4520
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - attrition_output_layer_accuracy: 0.8537 - attrition_output_layer_loss: 0.3741 - department_output_layer_accuracy: 0.9929 - department_output_layer_loss: 0.0417 - loss: 0.4158
Epoch 4/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_layer_accuracy: 0.8530 - attrition_output_layer_loss: 0.3625 - department_output_layer_accuracy: 0.9940 - department_output_layer_loss: 0.0302 - loss: 0.3927
Epoch 5/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - attrition_output_layer_accuracy: 0.

In [28]:
# Evaluate the model with the testing data
results = model.evaluate(X_test_scaled, {'department_output_layer': y_department_test, 'attrition_output_layer': y_attrition_test})
results

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_layer_accuracy: 0.7936 - attrition_output_layer_loss: 1.8915 - department_output_layer_accuracy: 0.5416 - department_output_layer_loss: 4.4626 - loss: 6.3899  


[5.174461841583252,
 3.5111420154571533,
 1.4666595458984375,
 0.8163265585899353,
 0.581632673740387]

In [29]:
# Print the accuracy for both department and attrition
print(f"Department Accuracy: {results[4]}")
print(f"Attrition Accuracy: {results[3]}")

Department Accuracy: 0.581632673740387
Attrition Accuracy: 0.8163265585899353


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. The accuracy is not the best metric to use on this data, because the y data is imbalance. We also need to look at f1 score.
2. We choose the softmax for department output layer, because the department is not binary.For attrition, we choose sigmoid because it is binary.
3. We can have more data to increae the balance of the data set. We can also have more columns on X values.We can add more layers as well.